name = "life-hud"
compatibility_date = "2024-01-01"

[site]
bucket = "./"
exclude = [
  "node_modules",
  ".git",
  "*.md",
  "package*.json",
  "*.lock",
  ".env*",
  "wrangler.toml",
  "supabase-migration.sql",
  "docs"
]
