name = "life-hud"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./"

# Static assets configuration
assets = { directory = "./", binding = "STATIC" }

# Exclude patterns for deployment
[env.production]
exclude = [
  "node_modules",
  ".git",
  "*.md",
  "package*.json",
  "*.lock",
  ".env*",
  "wrangler.toml",
  "supabase-migration.sql",
  "docs"
]
